### PR TITLE
[test] add mermaid support

### PR DESCRIPTION
**Pull request by XRSec**
Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

### CODE REVIEW

**Comment by huan** [comment]
Thank you very much for adding the mermaid support!

Please let me know when you finished testing and it's good to be merged.

**Comment by huan** [comment]
I think this PR is useful for our website, and I'd like to see it be keeping improved so that we can merge it after everything is good.

**Comment by XRSec** [comment]
@huan 这个环境我不太会使用，主要是启动方式我很懵，根据里面的docker 文档启动也有点问题😂

**Review by zhihuifanqiechaodan — APPROVED** [review]

**Comment by huan** [comment]
@zhihuifanqiechaodan thanks for the approval!

Could you confirm that this PR is working as expected?

**Comment by XRSec** [comment]
是不是需要重新发起PR，好像文件并没有更新

**Comment by zhihuifanqiechaodan** [comment]
> @zhihuifanqiechaodan thanks for the approval!
> 
> Could you confirm that this PR is working as expected?

我看到checks都通过了，sorry。

**Comment by huan** [comment]
That's all right.

This is a functional PR and we have merged it but it seems that not work as expected.

See:

- https://github.com/wechaty/jekyll/issues/102#issuecomment-1109788342

**Comment by XRSec** [comment]
我在HTML 开发者工具里面看了，并没有 unpkg.com 请求，说明 js 文件并没有生效

**Comment by huan** [comment]
Yeah, it seems that we missed something...

**Pull request closed without merging**
