### PR TITLE
shezhangbujianle

### PR DESCRIPTION
**Pull request by bigbrother666sh**
Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

### CODE REVIEW

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Comment by bigbrother666sh** [comment]
hi. I'am puzzled with this, 
ERROR: "lint:md" exited with 1.
ERROR: "lint" exited with 1.
Error: Process completed with exit code 1.

**Comment by huan** [comment]
We have a markdown linter to keep the style of our markdown text to be consistent.

From the CI we can see the below error messages:

```
jekyll/_posts/2022-03-31-shezhangbujianle.md:11:15 MD034/no-bare-urls Bare URL used [Context: "https://github.com/bigbrother6..."]
jekyll/_posts/2022-03-31-shezhangbujianle.md:21 MD002/first-heading-h1/first-header-h1 First heading should be a top-level heading [Expected: h2; Actual: h3]
jekyll/_posts/2022-03-31-shezhangbujianle.md:56 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "# 项目挑战"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:56 MD0[25](https://github.com/wechaty/jekyll/runs/5768558822?check_suite_focus=true#step:7:25)/single-title/single-h1 Multiple top-level headings in the same document [Context: "# 项目挑战"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:67 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "# 导演机制"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:67 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# 导演机制"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:68:158 MD034/no-bare-urls Bare URL used [Context: "https://github.com/wechaty"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:71 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]
jekyll/_posts/2022-03-31-shezhangbujianle.md:71 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "### 用户注册问题"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:75 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "### 主动消息发送"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:78 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "### 应急消息发送"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:86 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### 流程引导"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:91 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "# 回到作品本身，先有创意还是先有技术？"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:91 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# 回到作品本身，先有创意还是先有技术？"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:119 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# 致敬"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:1[27](https://github.com/wechaty/jekyll/runs/5768558822?check_suite_focus=true#step:7:27) MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# 写在最后的话"]
```

For example:

> jekyll/_posts/2022-03-31-shezhangbujianle.md:11:15 MD034/no-bare-urls Bare URL used [Context: "https://github.com/bigbrother6..."]

This means in the file 2022-03-31-shezhangbujianle.md at line 11, there has a Bare URL (raw url), which need to be quoted as being below diff demonstrated:

```diff
- https://github.com/bigbrother6...
+ <https://github.com/bigbrother6...>
```

For another example:

> jekyll/_posts/2022-03-31-shezhangbujianle.md:78 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "### 应急消息发送"]

This means in the file 2022-03-31-shezhangbujianle.md line 78, the heading line should add a blank line before and after it (surrounded), as the below diff demonstrated:

```diff
+ 
### 应急消息发送
+ 
```

Please help yourself to try to fix those issues, and feel free to let me know if you have more questions.

**Comment by bigbrother666sh** [comment]
thanks for your help @huan 
commit again

**Comment by huan** [comment]
> jekyll/_posts/2022-03-[31](https://github.com/wechaty/jekyll/runs/5782840311?check_suite_focus=true#step:7:31)-shezhangbujianle.md:16:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "##核心创意与演示"]

This means that you need to add a space between the `##` and `核心`:

```diff
- ##核心创意与演示
+ ## 核心创意与演示
```

Here are the other error messages, please feel free to comment here if you have any more questions:

```sh
jekyll/_posts/2022-03-31-shezhangbujianle.md:12 MD002/first-heading-h1/first-header-h1 First heading should be a top-level heading [Expected: h2; Actual: h1]
jekyll/_posts/2022-03-31-shezhangbujianle.md:12 MD0[25](https://github.com/wechaty/jekyll/runs/5782840311?check_suite_focus=true#step:7:25)/single-title/single-h1 Multiple top-level headings in the same document [Context: "# 借助世界上最大的单体中文NLP大模型和Wechaty，我..."]
jekyll/_posts/2022-03-31-shezhangbujianle.md:12:51 MD0[26](https://github.com/wechaty/jekyll/runs/5782840311?check_suite_focus=true#step:7:26)/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '!']
jekyll/_posts/2022-03-[31](https://github.com/wechaty/jekyll/runs/5782840311?check_suite_focus=true#step:7:31)-shezhangbujianle.md:16:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "##核心创意与演示"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:[32](https://github.com/wechaty/jekyll/runs/5782840311?check_suite_focus=true#step:7:32):1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###谭明VS蔡晓（AI)"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:[39](https://github.com/wechaty/jekyll/runs/5782840311?check_suite_focus=true#step:7:39):1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###孔墨VS蔡晓（AI)"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:46:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###李超VS蔡晓（AI)"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:52:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###孙若VS蔡晓（AI)"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:59:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###蔡晓（AI）在公聊（房间)"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:67:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "##项目挑战"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:79:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "##导演机制"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:85:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###用户注册问题"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:91:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###主动消息发送"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:95:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###应急消息发送"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:104:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "###流程引导"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:110:21 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2022-03-31-shezhangbujianle.md:110:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "##回到作品本身，先有创意还是先有技术?"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:139:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "##致敬"]
jekyll/_posts/2022-03-31-shezhangbujianle.md:147:1 MD018/no-missing-space-atx No space after hash on atx style heading [Context: "##写在最后的话"]
```

BTW: All the image files need to be saved locally instead reference them via other URLs, and the must be `.webp` format.

**Comment by huan** [comment]
> jekyll/_posts/2022-03-31-shezhangbujianle.md:12 MD002/first-heading-h1/first-header-h1 First heading should be a top-level heading [Expected: h2; Actual: h1]

The error message "Expected: h2; Actual: h1" tell us that, we should use h2 (##) instead of h1 (#)

**Comment by huan** [comment]
For publishing a blog post on our community website, there are lots of rules that need to be followed.

I'd like to recommend the below two blog posts for your reference:

1. [零基础小白在Wechaty社区发表自己的第一篇博客, @juzibot, Jul 02, 2021](https://wechaty.js.org/2021/07/02/how-to-publish-blog-on-wechaty/)
2. [入门：小白如何在wechaty社区发布自己的第一篇博客（一）, @atorber, Apr 22, 2021](https://wechaty.js.org/2021/04/22/how-to-publish-blog-on-wechaty/)

**Comment by bigbrother666sh** [comment]
@huan 是不是目前就三个问题了：
1、我需要 一个 jekyll/assets/contributors/bigbrother66sh/avatar.png （还望告知avater图片尺寸、格式要求）
2、需要把文件名改为 shezhang-bujian-le.md
3、把 tag中的AI改为ai
谢谢

**Comment by huan** [comment]
Yes, you need to fix those 3 issues first.

> 1、我需要 一个 jekyll/assets/contributors/bigbrother66sh/avatar.png（还望告知avater图片尺寸、格式要求）

.webp format, with its width no larger than 1920 pixels

> 2、需要把文件名改为 shezhang-bujian-le.md

Correct.

> 3、把 tag中的AI改为ai

It will be nice.

You are welcome!

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> [](https://github.com/wechaty)You've invited bigbrother666 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Comment by bigbrother666sh** [comment]
Cheers for the all!
thanks for your help again.

**Comment by huan** [comment]
You are welcome, and thank you very much for sharing your great post for the DM bot of 剧本杀！ :smiley:

**Comment by huan** [comment]
The published blog post at https://wechaty.js.org/2022/03/31/shezhang-bujian-le/ has some image 404 issues (due to the GFW problem)

We need to convert all the below code

```html
<img alt="img" height="480" src="https://github.com/bigbrother666sh/shezhangbujianle/blob/main/assets/vstanming.gif" width="960"/>
```

to markdown by saving the image file locally.

**Comment by huan** [comment]
After I reviewed the https://github.com/bigbrother666sh/shezhangbujianle/blob/main/assets/lastroom.gif, I believe this GIF should be better converted into a YouTube video because it's HUGE (almost 30MB).

Would you like to make a YouTube video to demonstrate your great DM bot? I believe that would make this post more attractive to the readers!

**Pull request merged**
