### PR TITLE
更新作者信息

### PR DESCRIPTION
**Pull request by Ran-Xing**
Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

### CODE REVIEW

**Comment by Ran-Xing** [comment]
根据相关博文 有两种支持方式

### 方案一：

_include 插入页面

```html
<script src="https://unpkg.com/mermaid@8.9.3/dist/mermaid.min.js"></script>
<script>
  $(document).ready(function () {
    mermaid.initialize({
      startOnLoad:true,
      theme: "default",
    });
    window.mermaid.init(undefined, document.querySelectorAll('.language-mermaid'));
  });
</script>
```

### 方案二

_layouts 插入页面

```html
{ % if page.mermaid % }

<script>
function initMermaid() {
  var config = {
    startOnLoad: true,
    theme: "forest",
    flowchart:{
      useMaxWidth: true,
      htmlLabels: true
    }
  };
  mermaid.initialize(config);
  window.mermaid.init(undefined, document.querySelectorAll('.language-mermaid'));
}
</script>

<script src="//cdnjs.cloudflare.com/ajax/libs/mermaid/8.6.0/mermaid.min.js"
  async
  onload="initMermaid()">
</script>

{ % endif % }
```

现在已经尝试过了方案一，这次提交的是方案二，希望一把过

**Comment by huan** [comment]
Could you please confirm the new code works in your local development box before we merge this PR? Because we should always submit the patch which has already confirmed work as expected.

thank you very much!

**Comment by Ran-Xing** [comment]
@huan 我无法确定，我缺少 jekyll 相关的知识，搭建也搭建不起来,而且还有很多报错，希望其他兄弟能尽快完善吧

**Comment by Ran-Xing** [comment]
@huan 拉取了新的代码，禁用了mermaid，能否先帮我把作者改了，mermaid 适配 我也没办法适配

**Comment by huan** [comment]
Hi, one PR should only implement one task, this PR has two, which should be limited to one.

Please keep this PR to be only mermaid-related or name related, and feel free to create another one to do the other.

Thank you very much.

**Comment by Ran-Xing** [comment]
其实mermai动不动都无所谓了，我感觉，因为上次已经合进去了，但是不生效，我的Mac没这么大性能，而且CPU不兼容，跑不了，用的是Apple芯片🤣

**Review by huan — APPROVED** [review]
LGTM

**Comment by Ran-Xing** [comment]
@huan im here

**Comment by huan** [comment]
Welcome back!

> You've invited 星冉 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

**Pull request merged**
